# Easier prefix
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Sensible pane splits
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# Quiet defaults
set-option -g visual-activity off
set-option -g visual-bell off
set-option -g visual-silence off
set-window-option -g monitor-activity off
set-option -g bell-action none
